### ISSUE TITLE
Connection à un compte

### ISSUE THREAD

**Issue by powerfulsheron** [JavaBetterThanPHP/CVbien#11]
### Récit métier

En tant qu'utilisateur ressource humaine
Je veux me connecter à l'application via mon compte pro
Afin de rechercher des profils

En tant qu’utilisateur développeur
Je veux pouvoir me connecter à l’application
Afin d’accéder à mon profil
 
### Scénarios

- S-1 :
Étant donné que je ne suis pas connecté à mon compte
lorsque je renseigne mon login et mon mot de passe
et que je clique sur "Se connecter"
alors je suis redirigé sur l'accueil de mon compte
- S-2 :
Étant donné que je ne suis pas connecté à mon compte
lorsque je renseigne un login et un mot de passe erroné 
et que je clique sur "Se connecter"
alors je suis redirigé sur la page de connexion 
- S-3 :
Étant donné que je me suis déjà connecté sur mon compte il y a moins de 30 minutes
et que je n'ai pas vidé mon cache et mes cookies
lorsque je ré accède à l'application
alors je suis déjà authentifié 
et je suis redirigé à la page d'accueil

### Règles de gestions

- RG-1 : Si le couple login + mot de passe ne figure pas dans la base de donnée, l'utilisateur est notifié d'une "erreur d'authentification" et est invité à créer un compte
- RG-2 : Une connexion réussie sauvegarde un token/cookie généré aléatoirement sur le navigateur de l'utilisateur pour assurer la session
- RG-3 : A partir de x tentatives ratées d'authentification, l'utilisateur est notifié par mail

![Mockup](https://raw.githubusercontent.com/JavaBetterThanPHP/CVbien/master/other/Mockups/login.png)

**Comment by froger22** [comment]
Back : auth terminée
Front : en cours @max-abl
