### ISSUE TITLE
Créer la partie Back et la partie Front

### ISSUE THREAD

**Issue by powerfulsheron** [JavaBetterThanPHP/CVbien#27]
### Technical Story
En tant que CVBien
Je veux pouvoir dissocier les fonctionnalités Administrateur et Utilisateur de l'application
Afin d'optimiser et de sécuriser le site

### Scénarios
- S-1 :  
Étant donné que je suis connecté sur l'application
et que j'ai un rôle Administrateur
Lorsque je rentre l'url "/admin"
Alors je suis redirigé sur la partie Back
et je peux administrer le site

- S-2 :  
Étant donné que je suis connecté sur l'application
et que j'ai un rôle Utilisateur
Lorsque j'accède à l'adresse "/dashboard"
Alors je suis redirigé sur la partie Front
et j'arrive sur mon espace personnel

- S-3 :  
Étant donné que je suis connecté sur l'application
et que j'ai un rôle Utilisateur
Lorsque je rentre l'url "/admin"
Alors une exception est levée

**Comment by froger22** [comment]
Terminé.

Les routes front sont "/", les routes back sont "/admin".

**Comment by powerfulsheron** [comment]
Moved from 3 to 5 estimate because of the rework and the complexity of the relations beetween entities
